export const UPDATE_CURSOR = 'update_cursor'
export const REDRAW_ROUND_TITLES = 'redraw_round_titles'
export const HANDLE_NEW_ANCHOR_ROUND = 'handle_new_anchor_round'
export const REDRAW_DYNAMIC_MATCHES = 'redraw_dynamic_matches'
export const UPDATE_CANVAS_SCROLLABILITY = 'update_canvas_scrollability'
export const FULL_REDRAW_MATCHES = 'full_redraw_matches'
export const UPDATE_VERT_BUTTONS_DISABLED_STATE = 'update_vert_buttons_disabled_state'
export const SCHEDULE_FORGET_SCROLL_Y = 'schedule_forget_scroll_Y'