export const CURSOR = 'cursor'
export const SCROLL = 'scroll'
export const SCROLL_X = 'scroll_X'
export const SCROLL_TO_NEW_ANCHOR_ROUND = 'anchor_scroll_round'
export const REDRAW_ALL = 'redraw_all'
export const REDRAW_EXPANDED_MATCHES = 'redraw_expanded_matches'
export const ANIMATE_EXPANDED_MATCH_CHANGE = 'animate_expanded_match_change'
